GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/1
###

GET http://localhost:3001/api/notes/29
###

DELETE  http://localhost:3001/api/notes/3

###
POST  http://localhost:3001/api/notes
content-type: application/json

{
    "content": "sample",
    "important": true
}

###

POST  http://localhost:3001/api/notes
content-type: application/json

{
    "content": "non-important sample"
}

