GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/1
###

GET http://localhost:3003/api/blogs/1/sa
###

DELETE  http://localhost:3003/api/blogs/3

###
POST  http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Arto Hellas",
    "author": "Some biography writer",
    "url": "arto-hellas",
    "likes": 8
}

###
POST  http://localhost:3003/api/users
content-type: application/json

{
    "username": "umurcan",
    "name": "umurcan",
    "password": "password"
}
